apiVersion: apps/v1
kind: Deployment
metadata:
  name: opstree
  labels:
    app: opstree
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  revisionHistoryLimit: 2
  paused: false
  minReadySeconds: 10
  selector:
    matchLabels:
      app: opstree
  template:
    metadata:
      name: opstree
      labels:
        app: opstree
    spec:
      containers:
        - name: opstree
          image: fmuhammad1824/wishtree:$BUILD_NUMBER
          ports:
            - containerPort:  9090
              protocol: TCP
          resources:
            limits:
              cpu: "200m"
              memory: "500Mi"
            requests:
              cpu: "100m"
              memory: "200Mi"

